// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSvaTHf8t5UXktSbPDbPTHMaF5zAC_0I',
    appId: '1:764547309861:web:79ea6e12fb48ff5477facc',
    messagingSenderId: '764547309861',
    projectId: 'ititask-557e4',
    authDomain: 'ititask-557e4.firebaseapp.com',
    storageBucket: 'ititask-557e4.appspot.com',
    measurementId: 'G-SH0JZDK6YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6mqXMyHisJO4bRat4wazHmEPMibZN44',
    appId: '1:764547309861:android:5d29fa7570f4d83d77facc',
    messagingSenderId: '764547309861',
    projectId: 'ititask-557e4',
    storageBucket: 'ititask-557e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWydQdkvsN7heTdcN5ycNnbzMz_AzG9U',
    appId: '1:764547309861:ios:b3e7b4a6bfb3da6777facc',
    messagingSenderId: '764547309861',
    projectId: 'ititask-557e4',
    storageBucket: 'ititask-557e4.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWydQdkvsN7heTdcN5ycNnbzMz_AzG9U',
    appId: '1:764547309861:ios:0cfa230cfd4d9bd877facc',
    messagingSenderId: '764547309861',
    projectId: 'ititask-557e4',
    storageBucket: 'ititask-557e4.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
